// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_to_the_edge_of_the_universe = "CgkI5LWipdwNEAIQDw"; // <GPGSID>
        public const string achievement_on_a_rail = "CgkI5LWipdwNEAIQBQ"; // <GPGSID>
        public const string achievement_train_station = "CgkI5LWipdwNEAIQBw"; // <GPGSID>
        public const string achievement_i_want_it_all = "CgkI5LWipdwNEAIQDA"; // <GPGSID>
        public const string achievement_long_long_train = "CgkI5LWipdwNEAIQCQ"; // <GPGSID>
        public const string leaderboard_high_score = "CgkI5LWipdwNEAIQAg"; // <GPGSID>
        public const string achievement_railway_tycoon = "CgkI5LWipdwNEAIQCA"; // <GPGSID>
        public const string achievement_to_the_edge_of_the_galaxy = "CgkI5LWipdwNEAIQDg"; // <GPGSID>
        public const string achievement_just_a_scratch = "CgkI5LWipdwNEAIQCg"; // <GPGSID>
        public const string achievement_to_the_edge_of_the_world = "CgkI5LWipdwNEAIQDQ"; // <GPGSID>
        public const string achievement_dont_stop_me_now = "CgkI5LWipdwNEAIQCw"; // <GPGSID>
        public const string achievement_star_collector = "CgkI5LWipdwNEAIQBA"; // <GPGSID>
        public const string achievement_first_coin = "CgkI5LWipdwNEAIQAQ"; // <GPGSID>
        public const string achievement_speed_of_light = "CgkI5LWipdwNEAIQAw"; // <GPGSID>
        public const string achievement_new_customer = "CgkI5LWipdwNEAIQBg"; // <GPGSID>

}

